export const Actions = {
    USER_INFO: 'USER_INFO',
    USER_INFO_SUCCESS: 'USER_INFO_SUCCESS',
    USER_INFO_ERROR: 'USER_INFO_ERROR',

    USER_TOKEN: 'USER_TOKEN',
    SET_LOADER: 'SET_LOADER',

    USER_LOGOUT: 'USER_LOGOUT',
    CASE_PARTIES: 'CASE_PARTIES',
    CATEGORY_CASE: 'CATEGORY_CASE',

    CLINIC_REQUEST: 'CLINIC_REQUEST',
    CLINIC_REQUEST_SUCCESS: 'CLINIC_REQUEST_SUCCESS',
    CLINIC_REQUEST_FAILED: 'CLINIC_REQUEST_FAILED'
}